# Generated by Django 6.0.1 on 2026-01-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('job_role', models.CharField(max_length=50)),
                ('attrition', models.CharField(max_length=5)),
                ('monthly_income', models.FloatField()),
                ('salary_band', models.CharField(max_length=20)),
                ('total_working_years', models.IntegerField()),
                ('years_at_company', models.IntegerField()),
                ('experience_group', models.CharField(max_length=20)),
                ('age_group', models.CharField(max_length=20)),
            ],
        ),
    ]
